import {use, useEffect, useState} from 'react'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import AppBar from '@mui/material/AppBar';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';

import Container from '@mui/material/Container';

import Toolbar from '@mui/material/Toolbar';
import Typography from '@mui/material/Typography';

/*   Use Effect = react hook like useState
    its goal is to fire an inner function upn some sort of lifescyle relation condition
    
        component mounts/loads in state changes
        
    specifically we want to useEffect to talk to external sytems --
      stuff outside the scope of responsibiity of our app that we still need to interac wot
      
      DONOT wnat local or interal loading componente/state etc -- to be held hostage by external behavious we have no control over. Since communicationg with external systems
      also almost always takes loner thatn local operations
      we also dont want our componanent loading to be held hostage by the slowness and relative relat int he external comms
      
      therefor useEffet is set up so that it fires only afte the componest icel. state loads in BINGO - ass04 gonna need this bish
      
      
      
      UseEffect 
          param 1 = the callback fucntion that should run when the funciton rusn
          param 2 = the dependency array - empty array means when component mounts [] its a meanign for something that has a meaning again more reasons js is stupid like english */ 

export default function Home() {
  const RANDOM_QUOTE_URL = 'https://api.quotable.io/random'
  const [quoteData, setQuoteData] = useState({
    quote: "Quote here.",
    author: "Author here"
  })

  const handleClick = () => {
    
    //use this style same as ASS01
    fetch(RANDOM_QUOTE_URL)
      .then((response)=> {
        return response.json()
      }).then((data)=> {
        setQuoteData({
          quote: data.content,
          author: data.author
        })
      })

  }

  // toggle reactStreict mode: to false
//useEffect - 
//    Effects are submissive ... tell them what to do and when to do it and they will be happy little subs <3

// hard no- strong limit - no no
  // useEffect(
  //   () => {console.log("component re-render / I am a terrible programmer or i hate my comuter or both")}
  // )

// use useEfect when chatting to the outside world

  useEffect(
  () => {console.log("quote was changed")},
  [quoteData] 
)


  return (
    <div>
      <Head>
        <title>We Love Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            We Love Quotes
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container maxWidth="sm">
          <Box
            sx={{
              bgcolor: 'background.paper',
              pt: 8,
              pb: 6,
            }}
          >
            <Typography variant="h5" align="center" color="text.primary" paragraph>
              {quoteData.quote}
            </Typography>
            <Typography
              component="h1"
              variant="h4"
              align="center"
              color="text.secondary"
              gutterBottom
            >
              {quoteData.author}
            </Typography>
            <Box
             display="flex"
             justifyContent="center"

            >
              <Button
                variant="contained"
                onClick={handleClick}
              >
                Get New Quote
              </Button>
            </Box>
          </Box>
        </Container>
      </main>
    </div>
  )
}
