import Head from "next/head";
import styles from "@/styles/Home.module.css";

// MUI components
import Container from '@mui/material/Container';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';


export default function Home() {
  return (
    <>
      <Head>
        <title>MUI intro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <Container maxWidth="md" sx={{backgroundColor: '#cccccc'}}>
          <Box sx={{ my: 4 }}>
           <Typography variant="h2" component="h2">
              MUI looks good.
            </Typography>
            <Typography variant="p" component="p">
              You can perhaps see why this is a popular package.
            </Typography>         
          </Box>
        </Container>
      </main>
    </>
  );
}


// Notes on STATE: NEXT CLASS
// (add these to next classes notes)
// state maintains somethign inthe code so it cannot be changed
// components run a functiona nd re-render automatically
// basically we cant jsut use JS variables becasue everything re-renders and basically resets to default
// state is how we store info outside the scope of the componsent so it stays pure from React
// if hte compnent re-renders - then when compnent runs again it pulls a new value from use state
// kinda like private fields getter / setter firstName, setFirstName