import Head from "next/head";
import styles from "@/styles/Home.module.css";

// MUI components
import Container from '@mui/material/Container';

export default function Home() {
  return (
    <>
      <Head>
        <title>MUI intro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Container maxWidth="lg">
          some content we'll add later
        </Container>
      </main>
    </>
  );
}