
/// THE OG FILE 


import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

//my components
import Hello from "../components/hello";
import NewConcept from "../components/NewConcept";
import Container from "../components/Container";
// make sure to change ./ to @ symbol to easily reach the root - need to add to jsconfig.json

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Container>
            <Hello /> 
            <NewConcept concept="WE" />
            <p>Can you see me?</p>  {/*  why was I able to see mine on local host 3000? */}
            <NewConcept concept="DID" />
            <NewConcept concept="STUFF" />
          </Container>
        </main>
      </div>
    </>
  );
}
