import Head from "next/head";

// MUI components
import Container from '@mui/material/Container';


export default function Home() {
  return (
    <>
      <Head>
        <title>MUI intro</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxWidth="md" style={{ background: '#cccccc' }}>
          some content we'll add later
        </Container>
      </main>
    </>
  );
}
